from dataclasses import dataclass


@dataclass
class ImageExifData:
    camera_make: str = ""
    camera_model: str = ""
    film_simulation: str = ""
    quality: str = ""
    dynamic_range: str = ""
    dynamic_range_setting: str = ""
    development_dynamic_range: str = ""
    white_balance: str = ""
    white_balance_fine_tune: str = ""
    color_temperature: str = ""
    highlight_tone: str = ""
    shadow_tone: str = ""
    color: str = ""
    sharpness: str = ""
    noise_reduction: str = ""
    clarity: str = ""
    color_chrome_effect: str = ""
    color_chrome_fx_blue: str = ""
    grain_effect_roughness: str = ""
    grain_effect_size: str = ""
    flash_mode: str = ""
    flash_exposure_comp: str = ""
    focus_mode: str = ""
    shutter_type: str = ""
    lens_modulation_optimizer: str = ""
    picture_mode: str = ""
    drive_mode: str = ""
    image_stabilization: str = ""
    iso: str = ""
    exposure_compensation: str = ""
    date_taken: str = ""
