# Generated by Django 6.0.3 on 2026-03-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('filepath', models.CharField(max_length=1024, unique=True)),
                ('camera_make', models.CharField(blank=True, default='', max_length=100)),
                ('camera_model', models.CharField(blank=True, default='', max_length=100)),
                ('film_simulation', models.CharField(blank=True, default='', max_length=100)),
                ('dynamic_range', models.CharField(blank=True, default='', max_length=100)),
                ('white_balance', models.CharField(blank=True, default='', max_length=100)),
                ('white_balance_fine_tune', models.CharField(blank=True, default='', max_length=200)),
                ('highlight_tone', models.CharField(blank=True, default='', max_length=100)),
                ('shadow_tone', models.CharField(blank=True, default='', max_length=100)),
                ('color', models.CharField(blank=True, default='', max_length=100)),
                ('sharpness', models.CharField(blank=True, default='', max_length=100)),
                ('noise_reduction', models.CharField(blank=True, default='', max_length=100)),
                ('clarity', models.CharField(blank=True, default='', max_length=100)),
                ('color_chrome_effect', models.CharField(blank=True, default='', max_length=100)),
                ('color_chrome_fx_blue', models.CharField(blank=True, default='', max_length=100)),
                ('grain_effect_roughness', models.CharField(blank=True, default='', max_length=100)),
                ('grain_effect_size', models.CharField(blank=True, default='', max_length=100)),
                ('iso', models.CharField(blank=True, default='', max_length=50)),
                ('exposure_compensation', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
