# Generated by Django 6.0.3 on 2026-03-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagerecipe',
            name='date_taken',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
