# Generated by Django 6.0.3 on 2026-03-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_imagerecipe_date_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerecipe',
            name='date_taken',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
