# Generated by Django 6.0.3 on 2026-03-10 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_imagerecipe_date_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerecipe',
            name='film_simulation',
            field=models.CharField(max_length=100),
        ),
    ]
