# Generated by Django 6.0.3 on 2026-03-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_imagerecipe_film_simulation'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagerecipe',
            name='development_dynamic_range',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='imagerecipe',
            name='drive_mode',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='imagerecipe',
            name='dynamic_range_setting',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='imagerecipe',
            name='flash_exposure_comp',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='imagerecipe',
            name='flash_mode',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='imagerecipe',
            name='focus_mode',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='imagerecipe',
            name='image_stabilization',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='imagerecipe',
            name='lens_modulation_optimizer',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='imagerecipe',
            name='picture_mode',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='imagerecipe',
            name='quality',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='imagerecipe',
            name='shutter_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='imagerecipe',
            name='film_simulation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
