# Generated by Django 6.0.3 on 2026-03-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_fujifilmrecipe_color_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fujifilmrecipe',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
