# Generated by Django 6.0.3 on 2026-03-15 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_remove_image_default_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='in_album',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
