# Generated by Django 6.0.3 on 2026-03-26 10:59

import src.data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_recipe_decimal_tonal_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fujifilmexif',
            name='name',
            field=models.CharField(blank=True, default='', max_length=25, validators=[src.data.models._validate_recipe_name]),
        ),
        migrations.AlterField(
            model_name='fujifilmrecipe',
            name='name',
            field=models.CharField(blank=True, default='', max_length=25, validators=[src.data.models._validate_recipe_name]),
        ),
    ]
