# Generated by Django 6.0.3 on 2026-03-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_restrict_recipe_name_to_25_ascii'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='fujifilmrecipe',
            constraint=models.UniqueConstraint(fields=('film_simulation', 'dynamic_range', 'd_range_priority', 'grain_roughness', 'grain_size', 'color_chrome_effect', 'color_chrome_fx_blue', 'white_balance', 'white_balance_red', 'white_balance_blue', 'highlight', 'shadow', 'color', 'sharpness', 'high_iso_nr', 'clarity', 'monochromatic_color_warm_cool', 'monochromatic_color_magenta_green'), name='unique_fujifilm_recipe', nulls_distinct=False),
        ),
    ]
