# Generated by Django 6.0.3 on 2026-03-30 07:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_add_unique_fujifilm_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='image',
            name='filepath',
            field=models.CharField(max_length=1024),
        ),
        migrations.AddConstraint(
            model_name='image',
            constraint=models.UniqueConstraint(fields=('filepath',), name='unique_image_filepath'),
        ),
    ]
