# Generated by Django 6.0.3 on 2026-04-14 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0024_image_rating_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='fujifilmrecipe',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_for_recipes', to='data.image'),
        ),
    ]
