# Generated by Django 6.0.3 on 2026-04-10 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0024_image_rating_default'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fujifilmrecipe',
            index=models.Index(fields=['film_simulation'], name='idx_recipe_film_sim'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['-taken_at', 'id'], name='idx_image_taken_id'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['-rating', '-taken_at', 'id'], name='idx_image_rating_taken'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['fujifilm_recipe', '-rating', '-taken_at'], name='idx_image_recipe_rating'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['is_favorite', '-taken_at'], name='idx_image_favorite_taken'),
        ),
    ]
