# Generated by Django 6.0.3 on 2026-05-10 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0026_recipecard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='fujifilm_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='images', to='data.fujifilmrecipe'),
        ),
    ]
